// Deterministic demo catalog. Used ONLY when Supabase env is absent (local dev,
// design review, Vercel previews). Read-only: nothing writes here, checkout and
// applications require real backends. All brands/labs/values are fictional.

import type { Category, Product, Review, Vendor } from "./types";

export const CATEGORIES: Category[] = [
  {
    slug: "hemp-flower", name: "Hemp Flower", ageRestricted: true, jurisdictionSensitive: true,
    description: "Federally compliant hemp flower from verified farms and brands, every listing tied to a batch-linked, admin-verified COA.",
    seoIntro: "Hemp flower on this marketplace is listed with structured lab data: delta-9 THC, total THC, CBD and CBG percentages, plus pesticide, heavy-metal, microbial and solvent panel statuses pulled from the certificate of analysis for the exact batch offered.",
    faqs: [
      { q: "How is hemp flower verified on this marketplace?", a: "Every listing requires a certificate of analysis for the exact batch being sold. Our compliance team cross-checks the uploaded COA file against the structured potency and safety data before a Verified COA badge can appear." },
      { q: "Can I see the lab that tested a product?", a: "Yes. Each product's compliance panel names the laboratory, the COA issue date, and the batch or lot number, so you can trace results to the source." },
      { q: "Why can't some products ship to my state?", a: "Checkout eligibility is evaluated per destination based on product category, cannabinoid type, and configurable jurisdiction rules. Listings stay visible for research even where checkout is restricted." },
    ],
    relatedGuides: [
      { label: "How to read a hemp COA", href: "https://buyhempflowernearme.com/how-to-read-a-hemp-coa/" },
      { label: "Hemp laws by state", href: "https://buyhempflowernearme.com/hemp-laws-by-state/" },
    ],
  },
  {
    slug: "cbd-flower", name: "CBD Flower", ageRestricted: true, jurisdictionSensitive: true,
    description: "CBD-dominant hemp flower cultivars with verified cannabinoid profiles.",
    seoIntro: "CBD flower listings show CBD percentage alongside delta-9 THC and total THC values from batch-linked COAs, plus full safety panel statuses.",
    faqs: [
      { q: "What counts as CBD flower here?", a: "Hemp flower where CBD is the dominant cannabinoid on the batch COA. The exact percentage is shown on every listing." },
    ],
    relatedGuides: [{ label: "CBD vs CBG vs THCA compared", href: "https://buyhempflowernearme.com/" }],
  },
  {
    slug: "cbg-flower", name: "CBG Flower", ageRestricted: true, jurisdictionSensitive: true,
    description: "CBG-dominant cultivars from verified growers.",
    seoIntro: "CBG flower listings publish CBG percentage from the batch COA along with complete safety panel results.",
  },
  {
    slug: "thca-flower", name: "THCA Flower", ageRestricted: true, jurisdictionSensitive: true,
    description: "THCA hemp flower where permitted — availability is destination-dependent and enforced at checkout.",
    seoIntro: "THCA flower is one of the most jurisdiction-sensitive hemp categories. Every listing shows THCA, delta-9 THC and total THC values from its batch COA, and checkout is dynamically restricted by destination rules. Product pages remain visible for research everywhere.",
    faqs: [
      { q: "Is THCA flower available in every state?", a: "No. Checkout eligibility is evaluated per destination. Where a destination is restricted, the listing shows a clear availability notice instead of a buy button." },
      { q: "Does this marketplace make legality claims?", a: "No. We publish verification status, lab data, and configurable destination rules. For legal questions, see the state-by-state guides on our education hub." },
    ],
    relatedGuides: [{ label: "Hemp laws by state", href: "https://buyhempflowernearme.com/hemp-laws-by-state/" }],
  },
  {
    slug: "pre-rolls", name: "Hemp Pre-Rolls", ageRestricted: true, jurisdictionSensitive: true,
    description: "Pre-rolled hemp flower from verified sellers.",
    seoIntro: "Pre-roll listings inherit the batch COA of the flower they contain, with lab, batch, and potency data shown on each product page.",
  },
  {
    slug: "thc-drinks", name: "Hemp-Derived THC Drinks", ageRestricted: true, jurisdictionSensitive: true,
    description: "Hemp-derived THC beverages from verified beverage brands.",
    seoIntro: "Beverage listings show per-serving cannabinoid content from batch COAs and are subject to destination-specific checkout rules.",
  },
  {
    slug: "gummies", name: "Gummies", ageRestricted: true, jurisdictionSensitive: true,
    description: "Hemp-derived cannabinoid gummies with structured per-piece dosing data.",
    seoIntro: "Gummy listings display per-piece and per-package cannabinoid content verified against batch COAs.",
  },
  {
    slug: "vapes", name: "Vapes", ageRestricted: true, jurisdictionSensitive: true,
    description: "Hemp-derived vaporizer products with full safety panel disclosure.",
    seoIntro: "Vape listings require residual solvent and heavy metal panel results in addition to potency data.",
  },
  {
    slug: "tinctures", name: "Tinctures", ageRestricted: true, jurisdictionSensitive: true,
    description: "Cannabinoid tinctures and oils with verified potency.",
    seoIntro: "Tincture listings show total and per-serving cannabinoid content from batch-linked COAs.",
  },
  {
    slug: "cbn-sleep", name: "CBN Sleep Products", ageRestricted: true, jurisdictionSensitive: true,
    description: "CBN-forward products with transparent cannabinoid ratios.",
    seoIntro: "CBN listings publish CBN, CBD and THC values per serving from the batch COA.",
  },
  {
    slug: "wellness", name: "Wellness Products", ageRestricted: false, jurisdictionSensitive: false,
    description: "Topicals, capsules, and hemp wellness products.",
    seoIntro: "Wellness listings include full ingredient disclosure and batch-linked lab data where applicable.",
  },
  {
    slug: "accessories", name: "Accessories", ageRestricted: false, jurisdictionSensitive: false,
    description: "Storage, grinders, and accessories from verified retailers.",
    seoIntro: "Accessory listings come from identity-verified sellers with tracked marketplace shipping.",
  },
  {
    slug: "wholesale", name: "Wholesale Products", ageRestricted: true, jurisdictionSensitive: true,
    description: "Bulk hemp supply from verified farms, manufacturers, and distributors with MOQ and tiered pricing.",
    seoIntro: "Wholesale listings show minimum order quantities and tiered bulk pricing from verified suppliers. Buyers complete a business profile and per-vendor approval before wholesale pricing unlocks.",
    faqs: [
      { q: "How do I unlock wholesale pricing?", a: "Create a buyer business profile with your company details, then request wholesale access from the supplier. Vendors approve wholesale buyers individually." },
    ],
    relatedGuides: [{ label: "Wholesale hemp flower research", href: "https://buyhempflowernearme.com/wholesale-hemp-flower/" }],
  },
  {
    slug: "farm-direct", name: "Farm Direct", ageRestricted: true, jurisdictionSensitive: true,
    description: "Buy directly from verified hemp farms.",
    seoIntro: "Farm Direct listings come from sellers verified as licensed hemp farms, with the Farm Direct badge granted only after document review.",
  },
  {
    slug: "manufacturer-direct", name: "Manufacturer Direct", ageRestricted: true, jurisdictionSensitive: true,
    description: "Buy directly from verified manufacturers.",
    seoIntro: "Manufacturer Direct listings come from document-verified manufacturers, including private-label capable partners.",
  },
];

export const VENDORS: Vendor[] = [
  {
    id: "v-1", slug: "blue-ridge-hemp-co", brandName: "Blue Ridge Hemp Co.",
    sellerType: "hemp_farm", country: "US", region: "NC", city: "Asheville",
    about: "Family-run hemp farm in the North Carolina Blue Ridge mountains growing small-batch, slow-cured hemp flower since 2018.",
    brandStory: "Started on six acres with two cultivars, Blue Ridge now runs a 40-acre licensed operation with on-site drying barns and full batch traceability from clone to cure.",
    seoDescription: "Blue Ridge Hemp Co. is an identity-verified hemp farm in Asheville, NC selling COA-verified hemp and CBD flower direct on the BHFNM Marketplace.",
    joinedAt: "2026-01-14", identityVerified: true, businessVerified: true, walletVerified: true,
    wholesaleEnabled: true, privateLabelEnabled: false,
    handlingDaysMin: 1, handlingDaysMax: 2,
    badges: ["identity_verified_seller","verified_coa","batch_linked_coa","recently_tested","marketplace_shipping_tracking","top_rated_seller","wholesale_capable","farm_direct","verified_brand"],
    ratingAvg: 4.9, ratingCount: 212, onTimeShipRate: 0.99, responseHours: 3, productCount: 14,
    policies: {
      shipping: "Orders ship within 1–2 business days via marketplace-generated tracked labels.",
      returns: "Damaged, wrong, or materially different items are covered by marketplace dispute protection within 48 hours of delivery.",
      support: "Messages answered within one business day through the marketplace inbox.",
    },
    faqs: [
      { q: "Do you test every batch?", a: "Yes — every harvest batch is tested by an independent lab and the COA is uploaded and verified before listing." },
      { q: "Do you offer bulk pricing?", a: "Yes, wholesale tiers start at 1 lb with approval through the marketplace wholesale program." },
    ],
  },
  {
    id: "v-2", slug: "solstice-labs", brandName: "Solstice Labs",
    sellerType: "manufacturer", country: "US", region: "CO", city: "Boulder",
    about: "cGMP-oriented cannabinoid manufacturer producing gummies, tinctures, and beverages with in-house formulation and third-party testing.",
    seoDescription: "Solstice Labs is a business-verified cannabinoid manufacturer in Boulder, CO offering manufacturer-direct and private-label products with verified COAs.",
    joinedAt: "2026-02-02", identityVerified: true, businessVerified: true, walletVerified: true,
    wholesaleEnabled: true, privateLabelEnabled: true,
    handlingDaysMin: 1, handlingDaysMax: 3,
    badges: ["identity_verified_seller","verified_coa","batch_linked_coa","marketplace_shipping_tracking","wholesale_capable","private_label_capable","manufacturer_direct","verified_brand"],
    ratingAvg: 4.8, ratingCount: 143, onTimeShipRate: 0.97, responseHours: 5, productCount: 22,
    policies: {
      shipping: "1–3 business day handling; tracked marketplace labels on every order.",
      returns: "Marketplace dispute protection applies; unopened manufacturing defects always covered.",
      support: "Business-hours support via marketplace inbox, Mon–Fri.",
    },
  },
  {
    id: "v-3", slug: "northern-lights-hemp", brandName: "Northern Lights Hemp",
    sellerType: "cbd_brand", country: "CA", region: "ON", city: "Toronto",
    about: "Canadian CBD brand focused on sleep and recovery formulations, sourcing from licensed Ontario producers.",
    seoDescription: "Northern Lights Hemp is a verified Canadian CBD brand in Toronto, ON selling COA-verified CBD and CBN products to Canadian buyers.",
    joinedAt: "2026-03-19", identityVerified: true, businessVerified: true, walletVerified: false,
    wholesaleEnabled: false, privateLabelEnabled: false,
    handlingDaysMin: 2, handlingDaysMax: 4,
    badges: ["identity_verified_seller","verified_coa","marketplace_shipping_tracking","verified_brand"],
    ratingAvg: 4.7, ratingCount: 67, onTimeShipRate: 0.95, responseHours: 8, productCount: 9,
    policies: {
      shipping: "Ships within Canada only. 2–4 business day handling with tracked labels.",
      returns: "48-hour marketplace dispute window applies after delivery.",
      support: "Replies within one business day.",
    },
  },
  {
    id: "v-4", slug: "high-plains-processing", brandName: "High Plains Processing",
    sellerType: "wholesaler", country: "US", region: "OK", city: "Tulsa",
    about: "Bulk hemp distributor supplying smokable flower, pre-roll inputs, and white-label services to retailers across the US.",
    seoDescription: "High Plains Processing is a verified hemp wholesaler in Tulsa, OK offering bulk COA-verified flower with tiered pricing on the BHFNM Marketplace.",
    joinedAt: "2026-04-08", identityVerified: true, businessVerified: true, walletVerified: true,
    wholesaleEnabled: true, privateLabelEnabled: true,
    handlingDaysMin: 2, handlingDaysMax: 5,
    badges: ["identity_verified_seller","verified_coa","batch_linked_coa","marketplace_shipping_tracking","wholesale_capable","private_label_capable"],
    ratingAvg: 4.6, ratingCount: 38, onTimeShipRate: 0.94, responseHours: 6, productCount: 11,
    policies: {
      shipping: "Freight and parcel options; 2–5 business day handling on bulk orders.",
      returns: "Bulk orders covered by marketplace dispute protection for verified shipment failures and materially different goods.",
      support: "Dedicated wholesale desk via marketplace inbox.",
    },
  },
];

const img = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=1200&q=70`;

export const PRODUCTS: Product[] = [
  {
    id: "p-1", slug: "appalachian-haze-cbd-flower", title: "Appalachian Haze CBD Flower",
    vendorSlug: "blue-ridge-hemp-co", categorySlug: "cbd-flower", subtype: "Greenhouse flower",
    shortDescription: "Slow-cured CBD-dominant flower, batch AH-2605, 17.2% CBD, verified COA.",
    description: "Appalachian Haze is a CBD-dominant cultivar grown in Blue Ridge's mountain greenhouses and slow-cured for 21 days. Batch AH-2605 tests at 17.2% CBD with 0.21% delta-9 THC, with passing pesticide, heavy metal, microbial and solvent panels from Foothills Analytical.",
    status: "live", cannabinoidType: "cbd",
    images: [
      { url: img("photo-1603909223429-69bb7101f420"), alt: "Appalachian Haze CBD hemp flower close-up" },
      { url: img("photo-1567861911437-538298e4232c"), alt: "Cured hemp flower in glass jar" },
    ],
    variants: [
      { id: "p1-35", sku: "AH-2605-3.5", name: "3.5 g", priceCents: 2400, stock: 62 },
      { id: "p1-7", sku: "AH-2605-7", name: "7 g", priceCents: 4200, stock: 41 },
      { id: "p1-28", sku: "AH-2605-28", name: "28 g", priceCents: 12900, stock: 18 },
      { id: "p1-lb", sku: "AH-2605-LB", name: "1 lb (wholesale)", priceCents: 89000, stock: 6, wholesaleOnly: true, wholesaleTiers: [{ minQuantity: 5, priceCents: 79000 }, { minQuantity: 10, priceCents: 69000 }] },
    ],
    compliance: {
      id: "c-1", batchNumber: "AH-2605", labName: "Foothills Analytical", labWebsite: "https://example-lab.test",
      coaIssueDate: "2026-05-18", retestDate: "2027-05-18",
      delta9ThcPct: 0.21, totalThcPct: 0.28, cbdPct: 17.2, cbgPct: 0.4,
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "not_tested", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-05-22", coaFileHash: "9f2b7c…e41a",
    },
    shippingOrigin: { country: "US", region: "NC" },
    handlingDaysMin: 1, handlingDaysMax: 2,
    restrictedJurisdictions: [],
    ageRestricted: true, wholesaleAvailable: true, wholesaleMoq: 1, privateLabelAvailable: false,
    ratingAvg: 4.9, ratingCount: 84,
    badges: ["verified_coa","batch_linked_coa","recently_tested","marketplace_shipping_tracking","farm_direct"],
    facts: {
      "Cannabinoid type": "CBD-dominant hemp flower",
      "CBD": "17.2%", "Delta-9 THC": "0.21%", "Total THC": "0.28%",
      "Batch": "AH-2605", "Lab": "Foothills Analytical", "COA issued": "2026-05-18",
      "Ships from": "North Carolina, US", "Handling time": "1–2 business days",
    },
    faqs: [
      { q: "Is this batch COA verified?", a: "Yes. Batch AH-2605's COA from Foothills Analytical was verified by marketplace compliance on 2026-05-22, including potency and safety panels." },
    ],
  },
  {
    id: "p-2", slug: "white-cbg-flower-frosted-cut", title: "White CBG Flower — Frosted Cut",
    vendorSlug: "blue-ridge-hemp-co", categorySlug: "cbg-flower", subtype: "Indoor flower",
    shortDescription: "Indoor CBG flower, batch WC-2604, 14.8% CBG, full panel verified.",
    description: "The White is a CBG-dominant cultivar grown indoors and hand-trimmed. Batch WC-2604 tests at 14.8% CBG and 0.09% delta-9 THC with passing full safety panels.",
    status: "live", cannabinoidType: "cbg",
    images: [{ url: img("photo-1536689318884-51372815ec9d"), alt: "White CBG hemp flower macro" }],
    variants: [
      { id: "p2-35", sku: "WC-2604-3.5", name: "3.5 g", priceCents: 2700, stock: 30 },
      { id: "p2-7", sku: "WC-2604-7", name: "7 g", priceCents: 4800, stock: 22 },
    ],
    compliance: {
      id: "c-2", batchNumber: "WC-2604", labName: "Foothills Analytical",
      coaIssueDate: "2026-04-30", retestDate: "2027-04-30",
      delta9ThcPct: 0.09, totalThcPct: 0.15, cbgPct: 14.8, cbdPct: 0.6,
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "not_tested", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-05-04", coaFileHash: "4c11ab…908d",
    },
    shippingOrigin: { country: "US", region: "NC" },
    handlingDaysMin: 1, handlingDaysMax: 2,
    restrictedJurisdictions: [], ageRestricted: true,
    wholesaleAvailable: false, privateLabelAvailable: false,
    ratingAvg: 4.8, ratingCount: 41,
    badges: ["verified_coa","batch_linked_coa","recently_tested","marketplace_shipping_tracking","farm_direct"],
    facts: {
      "Cannabinoid type": "CBG-dominant hemp flower", "CBG": "14.8%", "Delta-9 THC": "0.09%",
      "Batch": "WC-2604", "Lab": "Foothills Analytical", "Ships from": "North Carolina, US",
    },
  },
  {
    id: "p-3", slug: "sunset-gelato-thca-flower", title: "Sunset Gelato THCA Flower",
    vendorSlug: "high-plains-processing", categorySlug: "thca-flower", subtype: "Indoor flower",
    shortDescription: "Indoor THCA flower, batch SG-2606, 24.6% THCA — destination restrictions apply.",
    description: "Sunset Gelato is an indoor-grown THCA flower lot with dense, hand-trimmed buds. Batch SG-2606 tests at 24.6% THCA and 0.24% delta-9 THC. Checkout availability is evaluated per destination; this listing remains visible for research everywhere.",
    status: "live", cannabinoidType: "thca",
    images: [{ url: img("photo-1616690248299-bcb3bd2c8409"), alt: "Sunset Gelato THCA flower buds" }],
    variants: [
      { id: "p3-35", sku: "SG-2606-3.5", name: "3.5 g", priceCents: 3500, stock: 48 },
      { id: "p3-14", sku: "SG-2606-14", name: "14 g", priceCents: 11900, stock: 12 },
    ],
    compliance: {
      id: "c-3", batchNumber: "SG-2606", labName: "Redbud Testing Group",
      coaIssueDate: "2026-06-08", retestDate: "2027-06-08",
      delta9ThcPct: 0.24, totalThcPct: 21.8, thcaPct: 24.6, cbdPct: 0.1,
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "not_tested", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-06-11", coaFileHash: "77aa02…3f1c",
    },
    shippingOrigin: { country: "US", region: "OK" },
    handlingDaysMin: 2, handlingDaysMax: 4,
    restrictedJurisdictions: [{ country: "US", region: "ID" }, { country: "US", region: "KS" }, { country: "CA" }],
    ageRestricted: true, wholesaleAvailable: true, wholesaleMoq: 4, privateLabelAvailable: true,
    ratingAvg: 4.7, ratingCount: 29,
    badges: ["verified_coa","batch_linked_coa","recently_tested","marketplace_shipping_tracking","wholesale_capable"],
    facts: {
      "Cannabinoid type": "THCA hemp flower", "THCA": "24.6%", "Delta-9 THC": "0.24%", "Total THC": "21.8%",
      "Batch": "SG-2606", "Lab": "Redbud Testing Group", "Ships from": "Oklahoma, US",
      "Destination restrictions": "Not shippable to ID, KS, or Canada",
    },
    faqs: [
      { q: "Why can't I check out from my state?", a: "THCA flower checkout is controlled by destination rules configured by marketplace compliance. Where restricted, the page shows an availability notice instead of a buy button." },
    ],
  },
  {
    id: "p-4", slug: "solstice-sleep-gummies-cbn-cbd", title: "Solstice Sleep Gummies — CBN + CBD",
    vendorSlug: "solstice-labs", categorySlug: "cbn-sleep", subtype: "Gummies",
    shortDescription: "5 mg CBN + 25 mg CBD per gummy, 30-count, batch SL-G-2605, verified COA.",
    description: "Manufacturer-direct sleep gummies with 5 mg CBN and 25 mg CBD per piece, made in Solstice Labs' Boulder facility. Batch SL-G-2605 potency verified within 10% of label claim; full safety panels passing.",
    status: "live", cannabinoidType: "cbn",
    images: [{ url: img("photo-1611080626919-7cf5a9dbab5b"), alt: "Solstice Labs sleep gummies jar" }],
    variants: [
      { id: "p4-30", sku: "SL-G-2605-30", name: "30-count jar", priceCents: 3900, stock: 120 },
      { id: "p4-90", sku: "SL-G-2605-90", name: "90-count jar", priceCents: 9900, stock: 45 },
    ],
    compliance: {
      id: "c-4", batchNumber: "SL-G-2605", labName: "Front Range Labs",
      coaIssueDate: "2026-05-27", retestDate: "2027-05-27",
      delta9ThcPct: 0.0, totalThcPct: 0.0, cbdPct: 0, otherCannabinoids: { "CBN per piece (mg)": 5, "CBD per piece (mg)": 25 },
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "pass", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-05-30", coaFileHash: "b21d90…77e2",
    },
    shippingOrigin: { country: "US", region: "CO" },
    handlingDaysMin: 1, handlingDaysMax: 3,
    restrictedJurisdictions: [{ country: "CA" }],
    ageRestricted: true, wholesaleAvailable: true, wholesaleMoq: 24, privateLabelAvailable: true,
    ratingAvg: 4.8, ratingCount: 63,
    badges: ["verified_coa","batch_linked_coa","marketplace_shipping_tracking","manufacturer_direct","private_label_capable"],
    facts: {
      "Type": "CBN + CBD sleep gummies", "CBN per piece": "5 mg", "CBD per piece": "25 mg",
      "Batch": "SL-G-2605", "Lab": "Front Range Labs", "Ships from": "Colorado, US",
    },
  },
  {
    id: "p-5", slug: "northern-lights-cbd-tincture-1000", title: "Full-Spectrum CBD Tincture 1000 mg",
    vendorSlug: "northern-lights-hemp", categorySlug: "tinctures", subtype: "Oil tincture",
    shortDescription: "1000 mg full-spectrum CBD in MCT oil, batch NL-T-2604. Ships within Canada.",
    description: "Full-spectrum CBD tincture from licensed Ontario-grown hemp, 33 mg CBD per mL in organic MCT oil. Batch NL-T-2604 verified by Maple Analytics.",
    status: "live", cannabinoidType: "cbd",
    images: [{ url: img("photo-1590114065996-6cd9a48d90b1"), alt: "CBD tincture bottle with dropper" }],
    variants: [{ id: "p5-30", sku: "NL-T-2604-30", name: "30 mL", priceCents: 5400, stock: 80 }],
    compliance: {
      id: "c-5", batchNumber: "NL-T-2604", labName: "Maple Analytics",
      coaIssueDate: "2026-04-12", retestDate: "2027-04-12",
      delta9ThcPct: 0.18, totalThcPct: 0.22, cbdPct: 0, otherCannabinoids: { "CBD per mL (mg)": 33 },
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "pass", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-04-16", coaFileHash: "01fe3c…aa90",
    },
    shippingOrigin: { country: "CA", region: "ON" },
    handlingDaysMin: 2, handlingDaysMax: 4,
    restrictedJurisdictions: [{ country: "US" }],
    ageRestricted: true, wholesaleAvailable: false, privateLabelAvailable: false,
    ratingAvg: 4.7, ratingCount: 35,
    badges: ["verified_coa","marketplace_shipping_tracking"],
    facts: {
      "Type": "Full-spectrum CBD tincture", "CBD": "1000 mg total / 33 mg per mL",
      "Batch": "NL-T-2604", "Lab": "Maple Analytics", "Ships from": "Ontario, Canada",
      "Destination restrictions": "Ships within Canada only",
    },
  },
  {
    id: "p-6", slug: "bulk-hemp-flower-smalls-5lb", title: "Bulk Hemp Flower Smalls — 5 lb",
    vendorSlug: "high-plains-processing", categorySlug: "wholesale", subtype: "Bulk flower",
    shortDescription: "Machine-trimmed CBD smalls, batch HP-S-2605, 13.1% CBD. MOQ 1 unit (5 lb).",
    description: "Wholesale CBD flower smalls suited for pre-roll production. Batch HP-S-2605 tests at 13.1% CBD, 0.19% delta-9 THC. Tiered pricing for approved wholesale buyers.",
    status: "live", cannabinoidType: "cbd",
    images: [{ url: img("photo-1503262028195-93c528f03218"), alt: "Bulk hemp flower smalls" }],
    variants: [
      { id: "p6-5", sku: "HP-S-2605-5LB", name: "5 lb", priceCents: 240000, stock: 14, wholesaleOnly: true, wholesaleTiers: [{ minQuantity: 3, priceCents: 210000 }, { minQuantity: 6, priceCents: 185000 }] },
    ],
    compliance: {
      id: "c-6", batchNumber: "HP-S-2605", labName: "Redbud Testing Group",
      coaIssueDate: "2026-05-02", retestDate: "2027-05-02",
      delta9ThcPct: 0.19, totalThcPct: 0.26, cbdPct: 13.1,
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "not_tested", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-05-06", coaFileHash: "cc90e1…40b7",
    },
    shippingOrigin: { country: "US", region: "OK" },
    handlingDaysMin: 2, handlingDaysMax: 5,
    restrictedJurisdictions: [{ country: "CA" }],
    ageRestricted: true, wholesaleAvailable: true, wholesaleMoq: 1, privateLabelAvailable: true,
    ratingAvg: 4.6, ratingCount: 12,
    badges: ["verified_coa","batch_linked_coa","marketplace_shipping_tracking","wholesale_capable","private_label_capable"],
    facts: {
      "Type": "Wholesale CBD flower smalls", "CBD": "13.1%", "Delta-9 THC": "0.19%",
      "MOQ": "1 × 5 lb", "Batch": "HP-S-2605", "Ships from": "Oklahoma, US",
    },
  },
  {
    id: "p-7", slug: "solstice-lift-thc-seltzer", title: "Lift — Hemp-Derived THC Seltzer (4-pack)",
    vendorSlug: "solstice-labs", categorySlug: "thc-drinks", subtype: "Beverage",
    shortDescription: "5 mg hemp-derived delta-9 THC per can, batch SL-B-2606. Destination rules apply.",
    description: "Lift is a sparkling seltzer with 5 mg hemp-derived delta-9 THC per 12 oz can, produced at Solstice Labs' beverage line. Batch SL-B-2606 verified for per-serving potency and full safety panels.",
    status: "live", cannabinoidType: "delta9_hemp",
    images: [{ url: img("photo-1622543925917-763c34d1a86e"), alt: "THC seltzer cans on ice" }],
    variants: [{ id: "p7-4", sku: "SL-B-2606-4", name: "4-pack", priceCents: 2200, stock: 200 }],
    compliance: {
      id: "c-7", batchNumber: "SL-B-2606", labName: "Front Range Labs",
      coaIssueDate: "2026-06-01", retestDate: "2026-12-01",
      delta9ThcPct: 0, otherCannabinoids: { "Delta-9 THC per can (mg)": 5 },
      pesticides: "pass", heavyMetals: "pass", microbials: "pass", residualSolvents: "pass", foreignMaterial: "pass",
      status: "verified", verifiedAt: "2026-06-03", coaFileHash: "e0b4f2…19cd",
    },
    shippingOrigin: { country: "US", region: "CO" },
    handlingDaysMin: 1, handlingDaysMax: 3,
    restrictedJurisdictions: [{ country: "CA" }, { country: "US", region: "ID" }],
    ageRestricted: true, wholesaleAvailable: true, wholesaleMoq: 12, privateLabelAvailable: true,
    ratingAvg: 4.9, ratingCount: 51,
    badges: ["verified_coa","batch_linked_coa","recently_tested","marketplace_shipping_tracking","manufacturer_direct"],
    facts: {
      "Type": "Hemp-derived THC seltzer", "Delta-9 THC per can": "5 mg",
      "Batch": "SL-B-2606", "Lab": "Front Range Labs", "Ships from": "Colorado, US",
    },
  },
  {
    id: "p-8", slug: "cedar-stash-jar-uv-glass", title: "Cedar Stash Jar — UV Glass",
    vendorSlug: "blue-ridge-hemp-co", categorySlug: "accessories", subtype: "Storage",
    shortDescription: "UV-filtering glass jar with cedar lid, humidity-stable storage for 14 g.",
    description: "Airtight UV-filtering glass storage jar with a cedar lid and silicone seal, sized for up to 14 g of flower. No age restriction; ships US-wide.",
    status: "live", cannabinoidType: "none",
    images: [{ url: img("photo-1585386959984-a4155224a1ad"), alt: "UV glass stash jar with cedar lid" }],
    variants: [{ id: "p8-1", sku: "BR-JAR-14", name: "14 g jar", priceCents: 1800, stock: 90 }],
    shippingOrigin: { country: "US", region: "NC" },
    handlingDaysMin: 1, handlingDaysMax: 2,
    restrictedJurisdictions: [], ageRestricted: false,
    wholesaleAvailable: false, privateLabelAvailable: false,
    ratingAvg: 4.8, ratingCount: 22,
    badges: ["marketplace_shipping_tracking"],
    facts: { "Type": "UV glass storage jar", "Capacity": "14 g", "Ships from": "North Carolina, US" },
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r-1", productSlug: "appalachian-haze-cbd-flower", vendorSlug: "blue-ridge-hemp-co",
    author: "Marcus T.", ratingOverall: 5, ratingAccuracy: 5, ratingPackaging: 5, ratingShipping: 5, ratingCommunication: 5,
    title: "Exactly matches the COA", body: "Cross-checked the batch number on the jar against the COA on the listing — identical. Cure quality is excellent and shipping took two days with live tracking.",
    verifiedPurchase: true, createdAt: "2026-06-10",
  },
  {
    id: "r-2", productSlug: "appalachian-haze-cbd-flower", vendorSlug: "blue-ridge-hemp-co",
    author: "Dana R.", ratingOverall: 5, ratingAccuracy: 5, ratingPackaging: 4, ratingShipping: 5,
    title: "Smooth and consistent", body: "Second order of this batch. Consistent with the first, arrived sealed with humidity pack.",
    verifiedPurchase: true, createdAt: "2026-06-18",
  },
  {
    id: "r-3", productSlug: "sunset-gelato-thca-flower", vendorSlug: "high-plains-processing",
    author: "Priya K.", ratingOverall: 5, ratingAccuracy: 5, ratingPackaging: 5, ratingShipping: 4,
    title: "Top shelf", body: "Dense, frosty, and the lab numbers on the panel match the printed COA in the package.",
    verifiedPurchase: true, createdAt: "2026-06-21",
  },
  {
    id: "r-4", productSlug: "solstice-sleep-gummies-cbn-cbd", vendorSlug: "solstice-labs",
    author: "Jordan M.", ratingOverall: 5, ratingAccuracy: 5, ratingPackaging: 5, ratingShipping: 5, ratingCommunication: 5,
    title: "Dosing is accurate", body: "Consistent effect at one gummy. Appreciate the per-piece lab verification on the listing.",
    verifiedPurchase: true, createdAt: "2026-06-05",
  },
  {
    id: "r-5", productSlug: "solstice-lift-thc-seltzer", vendorSlug: "solstice-labs",
    author: "Alexis B.", ratingOverall: 5, ratingAccuracy: 5, ratingPackaging: 5, ratingShipping: 5,
    title: "Great low-dose option", body: "5 mg is exactly right. Cans arrived cold-packed and intact.",
    verifiedPurchase: true, createdAt: "2026-06-25",
  },
];
